### PR TITLE
Improved Mobile Responsiveness and UI Enhancements

### PR DESCRIPTION
**Pull request by StanzTheDev**
Enhanced the mobile responsiveness of the layout for better usability on smaller screens.
Added a shadow effect to the progress image.
Implemented a smoother hover transition for the theme-toggle button.

### CODE REVIEW

**Review by hasan-py — CHANGES_REQUESTED** [review]
Could you please fix the merge conflict?

**Review by StanzTheDev — COMMENTED** [review]
Resolved merge conflicts.

**Comment by DhanushNehru** [comment]
Hi @StanzTheDev still there are merge conflicts

**Review by hasan-py — CHANGES_REQUESTED** [review]
Again conflict :)

**Comment by DhanushNehru** [comment]
Closing this PR as there are conflicts. Raise a new PR if possible

**Pull request closed without merging**
