### PR TITLE
Language change

### PR DESCRIPTION
**Pull request by LucioPalmucci**
issue #4 
✔️ Title language logic applied in 5 languages and tested.
✔️ Progress bar languaje logic applied.
❌Could not test progress bar logic becuase the changes I made in the app.js did not show.

### CODE REVIEW

**Review by DhanushNehru — CHANGES_REQUESTED** [review]
Hi @LucioPalmucci the build is failing please check your code

Screenshot 2024-09-24 at 1 40 33 PM

**Comment by LucioPalmucci** [comment]
I tried to sync the language form the progress bar of the index.html, but i could only make the API change the text depending of the navigator language

**Review by DhanushNehru — CHANGES_REQUESTED** [review]
Please resolve merge conflicts @LucioPalmucci

**Comment by DhanushNehru** [comment]
Please pull the latest code and raise a new PR @LucioPalmucci

**Pull request closed without merging**
