### PR TITLE
Added custom date feature

### PR DESCRIPTION
**Pull request by AkshatGupta2005**
#2 Issue Fixed. Added a custom date feature. User can enter Custom date and will get progress with respect to current date.

Here is the screen shot - 
image

### CODE REVIEW

**Review by DhanushNehru — CHANGES_REQUESTED** [review]
Issue: Try Entering the same date, you will see an issue please check @AkshatGupta2005 

Screenshot 2024-10-19 at 3 09 06 PM

**Comment by AkshatGupta2005** [comment]
Okay let me have a look

**Comment by AkshatGupta2005** [comment]
@DhanushNehru Please have a look, I've changed the date setting so if same date is entered, it will push the end date by 1. 

Also please update your api with this app.js as it includes some changes of custom date feature, as if the event has not started or event has completed.

Please have a look and let me know.

**Review by DhanushNehru — CHANGES_REQUESTED** [review]
Hi @AkshatGupta2005 , no proper year validation, screen crashes when date is not properly given

Screenshot 2024-10-21 at 1 37 22 PM

**Comment by AkshatGupta2005** [comment]
@DhanushNehru Please have a look now.

**Comment by AkshatGupta2005** [comment]
@DhanushNehru

**Pull request merged**
